#!/bin/bash


time parallel -j 2 " echo {} && python3 -u /home/pete/Dropbox/Projects/CS-PRS-pipeline/PRScs/PRScs.py --ref_dir /mnt/disks/r5/PRS/ldblk_1kg_eur --bim_prefix /mnt/disks/r5/plink/R5.hm3.rsid --sst_file /mnt/disks/r5/PRS/cs/munge/AD_sumstats_Jansenetal.txt.munged.rsid --n_gwas 455258 --out_dir /mnt/disks/r5/PRS/cs/weights/AD_sumstats_Jansenetal.txt.parallel3  --chrom {} >  /mnt/disks/r5/PRS/cs/logs/AD_sumstats_Jansenetal.txt.{}.parallel3.weights.log " ::: 9 4 13 19 20 8 7 22 12 14 16 6 11 1 10 15 2 21 18 3 17 5 |& tee   /mnt/disks/r5/PRS/cs/logs/parallel3.log


time parallel -j 1 "echo {} && python3 -u /home/pete/Dropbox/Projects/CS-PRS-pipeline/PRScs/PRScs.py --ref_dir /mnt/disks/r5/PRS/ldblk_1kg_eur --bim_prefix /mnt/disks/r5/plink/R5.hm3.rsid --sst_file /mnt/disks/r5/PRS/cs/munge/AD_sumstats_Jansenetal.txt.munged.rsid --n_gwas 455258 --out_dir /mnt/disks/r5/PRS/cs/weights/AD_sumstats_Jansenetal.txt.single3  --chrom {} >  /mnt/disks/r5/PRS/cs/logs/AD_sumstats_Jansenetal.txt.{}.single3.weights.log  " ::: 9 4 13 19 20 8 7 22 12 14 16 6 11 1 10 15 2 21 18 3 17 5 |& tee   /mnt/disks/r5/PRS/cs/logs/single3.log

time parallel -j 2 " echo {} && python2 -u /home/pete/Dropbox/Projects/CS-PRS-pipeline/PRScs/PRScs.py --ref_dir /mnt/disks/r5/PRS/ldblk_1kg_eur --bim_prefix /mnt/disks/r5/plink/R5.hm3.rsid --sst_file /mnt/disks/r5/PRS/cs/munge/AD_sumstats_Jansenetal.txt.munged.rsid --n_gwas 455258 --out_dir /mnt/disks/r5/PRS/cs/weights/AD_sumstats_Jansenetal.txt.parallel2  --chrom {} >  /mnt/disks/r5/PRS/cs/logs/AD_sumstats_Jansenetal.txt.{}.parallel2.weights.log " ::: 9 4 13 19 20 8 7 22 12 14 16 6 11 1 10 15 2 21 18 3 17 5 |& tee   /mnt/disks/r5/PRS/cs/logs/parallel2.log

time parallel -j 1 "echo {} && python2 -u /home/pete/Dropbox/Projects/CS-PRS-pipeline/PRScs/PRScs.py --ref_dir /mnt/disks/r5/PRS/ldblk_1kg_eur --bim_prefix /mnt/disks/r5/plink/R5.hm3.rsid --sst_file /mnt/disks/r5/PRS/cs/munge/AD_sumstats_Jansenetal.txt.munged.rsid --n_gwas 455258 --out_dir /mnt/disks/r5/PRS/cs/weights/AD_sumstats_Jansenetal.txt.single2  --chrom {} >  /mnt/disks/r5/PRS/cs/logs/AD_sumstats_Jansenetal.txt.{}.single2.weights.log  " ::: 9 4 13 19 20 8 7 22 12 14 16 6 11 1 10 15 2 21 18 3 17 5 |& tee   /mnt/disks/r5/PRS/cs/logs/single2.log
